services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "8182:8182"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
    depends_on:
      - consul
      - keycloak
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8180:8180"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
    depends_on:
      - consul
  accounts:
    build:
      context: accounts
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "8181:8181"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-accounts:5434/accounts_db
      SPRING_DATASOURCE_USERNAME: accounts_user
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - consul
      - postgresql-accounts
      - keycloak
  postgresql-accounts:
    image: "postgres:17"
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: accounts_user
      POSTGRES_PASSWORD: 12345
      PGPORT: 5434
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5434"
    volumes:
      - ./accounts/pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  blocker:
    build:
      context: blocker
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
      - "8185:8185"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-blocker:5436/blocker_db
      SPRING_DATASOURCE_USERNAME: blocker_user
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - consul
      - postgresql-blocker
      - keycloak
  postgresql-blocker:
    image: "postgres:17"
    environment:
      POSTGRES_DB: blocker_db
      POSTGRES_USER: blocker_user
      POSTGRES_PASSWORD: 12345
      PGPORT: 5436
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5436:5436"
    volumes:
      - ./blocker/pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  transfer:
    build:
      context: transfer
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
      - "8186:8186"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
    depends_on:
      - consul
      - keycloak
  exchange:
    build:
      context: exchange
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
      - "8187:8187"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
    depends_on:
      - consul
      - keycloak
  notification:
    build:
      context: notification
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
      - "8183:8183"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-notification:5435/notification_db
      SPRING_DATASOURCE_USERNAME: notification_user
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - consul
      - postgresql-notification
      - keycloak
  postgresql-notification:
    image: "postgres:17"
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: 12345
      PGPORT: 5435
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5435"
    volumes:
      - ./notification/pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: "sh /consul/init/start.sh"
    volumes:
      - ./consul:/consul
  postgresql-keycloak:
    image: "postgres:17"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGPORT: 5430
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5430"
    volumes:
      - ./keycloak/pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  keycloak:
    image: bitnami/keycloak
    restart: always
    ports:
      - "8084:8084"
    environment:
      KEYCLOAK_HTTP_PORT: 8084
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgresql-keycloak
      KEYCLOAK_DATABASE_PORT: 5430
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgresql-keycloak:
        condition: service_healthy