services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
    depends_on:
      - consul
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    environment:
      SPRING_CONFIG_IMPORT: consul:consul:8500
    depends_on:
      - consul
  accounts:
    build:
      context: accounts
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-accounts:5434/accounts_db
      SPRING_DATASOURCE_USERNAME: accounts_user
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - consul
      - postgresql-accounts
  postgresql-accounts:
    image: "postgres:17"
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: accounts_user
      POSTGRES_PASSWORD: 12345
      PGPORT: 5434
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5434"
    volumes:
      - ./accounts/pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: "sh /consul/init/start.sh"
#    command: "agent -dev -ui -client=0.0.0.0 -data-dir=/consul/data"
#    command: ["agent", "-dev", "-ui", "-client=0.0.0.0", "-data-dir=/consul/data", "&&", "./consul", "kv", "import", "@import.json"]
#    command: ["agent", "-ui", "-client=0.0.0.0", "-data-dir=/consul/data"]
    volumes:
      - ./consul:/consul