server:
  port: 8082
spring:
  application:
    name: gateway-application
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      enabled: true
    gateway:
      routes:
        - id: accounts
          uri: "lb://${accounts-service-name}"
          predicates:
            - Path=/account-service/**
          filters:
            - TokenRelay
        - id: notification
          uri: "lb://${notification-service-name}"
          predicates:
            - Path=/notification/**
          filters:
            - TokenRelay
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            token-uri: ${keycloak_url:http://localhost:8084/realms/bank}/protocol/openid-connect/token
#        registration:
#          gateway-client:
#            provider: keycloak
#            client-id: gateway_client_id
#            client-secret: 8jRYUyFquHKqenM8Edatj090NUE4ArIG
#            scope: accounts.read, accounts.write
#            authorization-grant-type: client_credentials
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      show-details: always
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    org:
      springframework: TRACE