server:
  port: 8082
spring:
  application:
    name: gateway-application
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      enabled: true
    gateway:
      routes:
        - id: accounts
          uri: "lb://${accounts-service-name}"
          predicates:
            - Path=/account-service/**
          filters:
            - TokenRelay
            - RemoveRequestHeader=JSESSIONID
        - id: notification
          uri: "lb://${notification-service-name}"
          predicates:
            - Path=/notification/**
          filters:
            - TokenRelay
            - RemoveRequestHeader=JSESSIONID
        - id: blocker
          uri: "lb://${blocker-service-name}"
          predicates:
            - Path=/blocker/**
          filters:
            - TokenRelay
            - RemoveRequestHeader=JSESSIONID
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      show-details: always
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
