server:
  port: 8082
spring:
  application:
    name: gateway-application
  config:
    import: consul:localhost:8500
  cloud:
    consul:
      enabled: true
    gateway:
      routes:
        - id: accounts
          uri: "lb://${accounts-service-name}"
          predicates:
            - Path=/account-service/**
          filters:
            - RewritePath=/account-service/?(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      show-details: always
    health:
      show-details: always
      probes:
        enabled: true