keycloak_client_id: cash
spring:
  application:
    name: cash-application
  cloud:
    consul:
      config:
        enabled: true
  config:
    import: optional:consul:localhost:8500
  security:
    oauth2:
      client:
        registration:
          cash:
            provider: keycloak
            client-id: cash_client_id
            client-secret: 4aikEhTgPTiO8oDipITLtvuYaBEDvziV
            authorization-grant-type: client_credentials
            scope: accounts.read, accounts.write, notification.write, blocker.write
        provider:
          keycloak:
            token-uri: ${keycloak_url:http://localhost:8084/realms/bank}/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak_url:http://localhost:8084/realms/bank}/protocol/openid-connect/certs
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 10
        failureRateThreshold: 10
        waitDurationInOpenState: 60s
        minimumNumberOfCalls: 5
    instances:
      notificationCircuitBreaker:
        baseConfig: default
      accountsCircuitBreaker:
        baseConfig: default
  retry:
    configs:
      default:
        failAfterMaxAttempts: true
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.lang.Exception
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      show-details: always
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: '*'
          show-details: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
    io:
      github:
        resilience4j: DEBUG
    ru:
      yandex:
        practicum:
          bliushtein:
            mod3: DEBUG