services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: ["agent", "-dev", "-ui", "-client=0.0.0.0", "-data-dir=/consul/data"]
    volumes:
      - ./data:/consul/data