keycloak_client_id: gateway-client
spring:
  application:
    name: ui-application
  cloud:
    consul:
      config:
        enabled: true
#        format: YAML
#        data-key: data
  config:
    import: consul:localhost:8500
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${keycloak_url:http://localhost:8084/realms/bank}/protocol/openid-connect/token
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway_client_id
            client-secret: 8jRYUyFquHKqenM8Edatj090NUE4ArIG
            scope: accounts.read, accounts.write
            authorization-grant-type: client_credentials
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      show-details: always
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    org:
      springframework: DEBUG