keycloak_client_id: gateway-client
spring:
  application:
    name: ui-application
  cloud:
    consul:
      config:
        enabled: true
#        format: YAML
#        data-key: data
  config:
    import: consul:localhost:8500
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${keycloak_url:http://localhost:8084/realms/bank}/protocol/openid-connect/token
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway_client_id
            client-secret: 8jRYUyFquHKqenM8Edatj090NUE4ArIG
            scope: accounts.read, accounts.write
            authorization-grant-type: client_credentials
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 10
        failureRateThreshold: 10
        waitDurationInOpenState: 60s
        minimumNumberOfCalls: 5
    instances:
      uiCircuitBreaker:
        baseConfig: default
  retry:
    configs:
      default:
        failAfterMaxAttempts: true
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.lang.Exception
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      show-details: always
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
    io:
      github:
        resilience4j: DEBUG
    ru:
      yandex:
        practicum:
          bliushtein:
            mod3: DEBUG