spring:
  application:
    name: ui-application
  cloud:
    consul:
      config:
        enabled: true
#        format: YAML
#        data-key: data
  config:
    import: consul:localhost:8500
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      show-details: always
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    org:
      springframework: DEBUG